### ISSUE TITLE
Improve Bundle Server

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#220]

**Comment by misaakidis** [comment]
Going to POST to http://127.0.0.1:3095/insert
Response from bundle inserter
Error while fetching: URL failed validation and a bundle will not be inserted for: http://feedproxy.google.com/~r/maryamina/L��Y�R^Q����LRKstored

Dec 12, 2015 10:37:35:483 Successfully inserted a bundle for http://feedproxy.google.com/~r/maryamina/~3/QgUHFZjF91I/.

**Comment by misaakidis** [comment]
Dec 12, 2015 13:37:35:707 Feed URL is http://chaay.ghoddusi.com/feed
reading feed direction from databaseDec 12, 2015 13:37:35:707 reading feed info from database
Dec 12, 2015 13:37:35:708 feed info: http://chaay.ghoddusi.com/feed یک لیوان چای داغ rtl
Dec 12, 2015 13:37:35:708 Feed direction is rtl
Error making request
Get http://127.0.0.1:3094/?url=aHR0cDovL2NoYWF5Lmdob2RkdXNpLmNvbS8lZDglYTclZDglYjclZDklODQlZDglYTclZDglYjklZGIlOGMlZDklODctJWQ5JWJlJWQ4JWIwJWRiJThjJWQ4JWIxJWQ4JWI0LSVkOCVhZiVkOCVhNyVkOSU4NiVkOCViNCVlMiU4MCU4YyVkOCVhYyVkOSU4OCVkYiU4Yy0lZDglYWYlZGElYTklZDglYWElZDglYjElZDglYTcv&direction=rtl: read tcp 127.0.0.1:3094: connection reset by peer
Dec 12, 2015 16:31:13:871 Failed to created a bundle for http://chaay.ghoddusi.com/%d8%a7%d8%b7%d9%84%d8%a7%d8%b9%db%8c%d9%87-%d9%be%d8%b0%db%8c%d8%b1%d8%b4-%d8%af%d8%a7%d9%86%d8%b4%e2%80%8c%d8%ac%d9%88%db%8c-%d8%af%da%a9%d8%aa%d8%b1%d8%a7/.
Error making request

**Comment by misaakidis** [comment]
info: Making request with options:  url=http://ir0.mobify.com/60/http://zoomg.ir/wp-content/uploads/2015/12/zoomg-ps4-community.jpg, encoding=null
Dec 19, 2015 19:41:53:293 [BUNDLE SERVER] Bundle is RTL
error: ------ERROR------ in wrappedRequest
read ECONNRESET
info: URL: http://www.zoomit.ir/cache/widgetkit/gallery/1205/IMG_0005-2b532271cb.jpg
Dec 19, 2015 19:41:54:204 [BUNDLE SERVER] Encountered error creating bundle for http://www.zoomit.ir/articles/tablet/26546-apple-ipad-pro-review.
Dec 19, 2015 19:41:54:204 [BUNDLE SERVER] Error: read ECONNRESET
error: ------ERROR------ in wrappedRequest
read ECONNRESET
info: URL: http://www.zoomit.ir/media/k2/items/cache/3f1feb244586d9e4240067268a28773c_XS.jpg
Dec 19, 2015 19:41:54:205 [BUNDLE SERVER] Encountered error creating bundle for http://www.zoomit.ir/articles/tablet/26546-apple-ipad-pro-review.
Dec 19, 2015 19:41:54:205 [BUNDLE SERVER] Error: read ECONNRESET
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:422:15)
    at Bundler.callback (/root/ceno/ceno-bridge/bshandler.js:210:15)
    at Request._callback (/root/ceno/ceno-bridge/node_modules/equalitie-bundler/src/bundler.js:135:23)
    at self.callback (/root/ceno/ceno-bridge/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/root/ceno/ceno-bridge/node_modules/request/request.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
